// Code generated by GoGamePlug DO NOT EDIT.

package R

var (
	MAP     = newMap_x1vqehn3njaae2qh()
	RAW     = newRaw_7d9vk955lhnzpt13()
	AUDIO   = newAudio_67id953vo70i5i7g()
	IMAGE   = newImage_mpcls9ydl9c8v92o()
	SHADER  = newShader_7fc9sal81jxry7i3()
	SPRITE  = newSprite_931gjyjgzxnr9ily()
	TILESET = newTileset_hzloy8jidwinn9vt()
	CLASS   = newClass_owwt0e7s18imublu()
	LAYER   = newLayer_z7x7a8t4oa224ewh()
	OBJECT  = newObject_8te5cg8o8p408hth()
	PROP    = newProp_v8gqy81pr43px2bj()
)

type map_x1vqehn3njaae2qh struct {
	MAIN string
}

func newMap_x1vqehn3njaae2qh() *map_x1vqehn3njaae2qh {
	return &map_x1vqehn3njaae2qh{MAIN: "res/map/main.tmx"}
}

type raw_7d9vk955lhnzpt13 struct {
	IPIX string
}

func newRaw_7d9vk955lhnzpt13() *raw_7d9vk955lhnzpt13 {
	return &raw_7d9vk955lhnzpt13{IPIX: "res/raw/ipix.ttf"}
}

type audio_67id953vo70i5i7g struct {
}

func newAudio_67id953vo70i5i7g() *audio_67id953vo70i5i7g {
	return &audio_67id953vo70i5i7g{}
}

type image_mpcls9ydl9c8v92o struct {
}

func newImage_mpcls9ydl9c8v92o() *image_mpcls9ydl9c8v92o {
	return &image_mpcls9ydl9c8v92o{}
}

type shader_7fc9sal81jxry7i3 struct {
}

func newShader_7fc9sal81jxry7i3() *shader_7fc9sal81jxry7i3 {
	return &shader_7fc9sal81jxry7i3{}
}

type sprite_931gjyjgzxnr9ily struct {
}

func newSprite_931gjyjgzxnr9ily() *sprite_931gjyjgzxnr9ily {
	return &sprite_931gjyjgzxnr9ily{}
}

type tileset_hzloy8jidwinn9vt struct {
}

func newTileset_hzloy8jidwinn9vt() *tileset_hzloy8jidwinn9vt {
	return &tileset_hzloy8jidwinn9vt{}
}

type class_owwt0e7s18imublu struct {
	CARD_AREA string
	CARD_PILE string
	ROUND     string
	TIP       string
	PLAYER    string
	INFO      string
}

func newClass_owwt0e7s18imublu() *class_owwt0e7s18imublu {
	return &class_owwt0e7s18imublu{CARD_AREA: "card_area", CARD_PILE: "card_pile", ROUND: "round", TIP: "tip", PLAYER: "player", INFO: "info"}
}

type layer_z7x7a8t4oa224ewh struct {
	UI   string
	BASE string
}

func newLayer_z7x7a8t4oa224ewh() *layer_z7x7a8t4oa224ewh {
	return &layer_z7x7a8t4oa224ewh{UI: "ui", BASE: "base"}
}

type object_8te5cg8o8p408hth struct {
	E_DECK     string
	P1         string
	P2         string
	E_CEMETERY string
	P3         string
	P4         string
	E10        string
	P5         string
	P6         string
	P7         string
	P8         string
	P9         string
	ENEMY      string
	P10        string
	E_EXTRA    string
	P_DECK     string
	P_CEMETERY string
	E_EXCEPT   string
	TIP        string
	P_EXTRA    string
	P_EXCEPT   string
	PLAYER     string
	INFO       string
	E1         string
	E2         string
	E3         string
	E4         string
	E5         string
	E6         string
	E7         string
	E8         string
	ROUND      string
	E9         string
}

func newObject_8te5cg8o8p408hth() *object_8te5cg8o8p408hth {
	return &object_8te5cg8o8p408hth{E_DECK: "e_deck", P1: "p1", P2: "p2", E_CEMETERY: "e_cemetery", P3: "p3", P4: "p4", E10: "e10", P5: "p5", P6: "p6", P7: "p7", P8: "p8", P9: "p9", ENEMY: "enemy", P10: "p10", E_EXTRA: "e_extra", P_DECK: "p_deck", P_CEMETERY: "p_cemetery", E_EXCEPT: "e_except", TIP: "tip", P_EXTRA: "p_extra", P_EXCEPT: "p_except", PLAYER: "player", INFO: "info", E1: "e1", E2: "e2", E3: "e3", E4: "e4", E5: "e5", E6: "e6", E7: "e7", E8: "e8", ROUND: "round", E9: "e9"}
}

type prop_v8gqy81pr43px2bj struct {
	TYPE    string
	MONSTER string
	PLAYER  string
}

func newProp_v8gqy81pr43px2bj() *prop_v8gqy81pr43px2bj {
	return &prop_v8gqy81pr43px2bj{TYPE: "type", MONSTER: "monster", PLAYER: "player"}
}
